name: Backend CI/CD with SSH Deploy
on:
  push:
    branches:
      - develop
      - backend-develop
      - main
jobs:
  build-push-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: "21"
          distribution: temurin
      - name: Create application.yml
        run: |
          mkdir -p ./backend/personal-folio/src/main/resources
          echo "${{ secrets.APPLICATION_YML_B64 }}" | base64 -d \
            > ./backend/personal-folio/src/main/resources/application.yml
      - name: Make gradlew executable
        run: chmod +x ./gradlew
        working-directory: ./backend/personal-folio
      - name: Build Spring Boot app
        run: ./gradlew clean build
        working-directory: ./backend/personal-folio
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./backend/personal-folio
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/backend:latest
      - name: Deploy with Docker Compose
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          capture_stdout: true
          script: |
            cd ~/app/Personal-folio
            sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/backend:latest
            sudo docker compose rm -sf backend
            sudo docker compose up -d backend
